name: MLOps Foundations CI/CD

on:
  push:
    branches: [ dev ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          python lint_model.py

      - name: Test with pytest
        run: |
          python -m pytest

  deploy:
    needs: build # Ensure build passes before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install joblib  # Add this step
        run: pip install joblib

      - name: Run deployment script
        run: python deploy.py
